In [1]:
import numpy as np
import random

### 2

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(a)
print(b)
print(a+b)
print(a @ b)

[[ 1 -2]
 [ 3  0]]
[[ 4 -1]
 [ 0  5]]
[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


### 3

In [3]:
a2 = np.array([[1, 7], [3, -6]])
b2 = np.array([[0, 5], [2, -1]])
c2 = np.array([[2, -4], [1, 1]])
print(a2)
print(b2)
print(c2)
print(3*a2-2*b2+4*c2)

[[ 1  7]
 [ 3 -6]]
[[ 0  5]
 [ 2 -1]]
[[ 2 -4]
 [ 1  1]]
[[ 11  -5]
 [  9 -12]]


### 4

In [4]:
a3 = np.array([[4, 1], [5, -2], [2, 3]])
print(a3)
print(a3.T)
print(a3 @ a3.T)
print(a3.T @ a3)

[[ 4  1]
 [ 5 -2]
 [ 2  3]]
[[ 4  5  2]
 [ 1 -2  3]]
[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


### 5

In [5]:
def matrixmult(m1,m2):
    s=0     #сумма
    t=[]    #временная матрица
    m3=[] # конечная матрица
    if len(m2)!=len(m1[0]):
        print("Матрицы не могут быть перемножены")
    else:
        r1=len(m1) #количество строк в первой матрице
        c1=len(m1[0]) #Количество столбцов в 1 и строк во 2ой матрице
        c2=len(m2[0]) #количество столбцов во 2ой матрице
        for z in range(r1):
            for j in range(c2):
                for i in range(c1):
                   s=s+m1[z][i]*m2[i][j]
                t.append(s)
                s=0
            m3.append(t)
            t=[]
    return m3



m3=matrixmult([[4, 1, 3], [10, 5, 1], [8, 10, 6]], [[4, 7, 4], [9, 4, 3], [2, 2, 8]])
print(m3)

[[31, 38, 43], [87, 92, 63], [134, 108, 110]]


In [6]:
#Проверяю себя через numpy
n1 = np.array([[4, 1, 3], [10, 5, 1], [8, 10, 6]])
n2 = np.array([[4, 7, 4], [9, 4, 3], [2, 2, 8]])
n1 @ n2

array([[ 31,  38,  43],
       [ 87,  92,  63],
       [134, 108, 110]])