### 1 и 5
Напишу функию метода Крамера используя numpy. Основная причина: не нашел стандартной библиотеки которая считает методом крамера. В 5ом задании не указано каким путем написать функцию, удобнее и корректнее использовать numpy и таким образом решить сразу 2 задачи

In [1]:
#В функции решил округлять значения до целого, чтобы решения были более красивыми
import numpy as np
from copy import copy
def kramer(M:np.array, M_right:np.array):
    det_main = np.linalg.det(M)
    if det_main != 0:
        solutions = []
        for i in range(M.shape[len(M.shape)-1]):
            m = copy(M)
            m[::, i] = M_right
            solutions.append(round(np.linalg.det(m)/det_main))
        return solutions
    else:
        return 'Система неопределена, не решается методом Крамера'

print(f'a. Ответ:{kramer(np.array([[1, -2], [3, -4]]), np.array([1, 7]))}')
print(f'б. Ответ:{kramer(np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]]), np.array([10, -2, 1]))}')

a. Ответ:[5, 2]
б. Ответ:[2, -1, 1]


### 2
Взял набор готовых функций из гугла, для реализации

In [2]:
def decompose_to_LU(a):
    """Decompose matrix of coefficients to L and U matrices.
     L and U triangular matrices will be represented in a single nxn matrix.
    :param a: numpy matrix of coefficients
    :return: numpy LU matrix
    """
    # create emtpy LU-matrix
    lu_matrix = np.matrix(np.zeros([a.shape[0], a.shape[1]]))
    n = a.shape[0]

    for k in range(n):
        # calculate all residual k-row elements
        for j in range(k, n):
            lu_matrix[k, j] = a[k, j] - lu_matrix[k, :k] * lu_matrix[:k, j]
        # calculate all residual k-column elemetns
        for i in range(k + 1, n):
            lu_matrix[i, k] = (a[i, k] - lu_matrix[i, : k] * lu_matrix[: k, k]) / lu_matrix[k, k]

    return lu_matrix

def get_L(m):
    """Get triangular L matrix from a single LU-matrix
    :param m: numpy LU-matrix
    :return: numpy triangular L matrix
    """
    L = m.copy()
    for i in range(L.shape[0]):
            L[i, i] = 1
            L[i, i+1 :] = 0
    return np.matrix(L)


def get_U(m):
    """Get triangular U matrix from a single LU-matrix
    :param m: numpy LU-matrix
    :return: numpy triangular U matrix
    """
    U = m.copy()
    for i in range(1, U.shape[0]):
        U[i, :i] = 0
    return U

def solve_LU(lu_matrix, b):
    """Solve system of equations from given LU-matrix and vector b of absolute terms.
    :param lu_matrix: numpy LU-matrix
    :param b: numpy matrix of absolute terms [n x 1]
    :return: numpy matrix of answers [n x 1]
    """
    # get supporting vector y
    y = np.matrix(np.zeros([lu_matrix.shape[0], 1]))
    for i in range(y.shape[0]):
        y[i, 0] = b[i, 0] - lu_matrix[i, :i] * y[:i]

    # get vector of answers x
    x = np.matrix(np.zeros([lu_matrix.shape[0], 1]))
    for i in range(1, x.shape[0] + 1):
        x[-i, 0] = (y[-i] - lu_matrix[-i, -i:] * x[-i:, 0] )/ lu_matrix[-i, -i]

    return x

In [3]:
lu1 = decompose_to_LU(np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]]))
l1 = get_L(lu1)
l1

matrix([[1., 0., 0.],
        [2., 1., 0.],
        [3., 4., 1.]])

In [4]:
lu2 = decompose_to_LU(np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]]))
l2 = get_L(lu2)
l2

matrix([[1., 0., 0., 0.],
        [2., 1., 0., 0.],
        [3., 5., 1., 0.],
        [4., 6., 7., 1.]])

### 3
Также применю предыдущие функции

In [5]:
a3 = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
a3_right = np.array([[1, -6, -5]])
lu3 = decompose_to_LU(a3)
solve_LU(lu3, a3_right.T).T

matrix([[-1.,  0.,  1.]])

### 4
Использую numpy

In [6]:
a4 = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
a4_right = np.array([531, -460, 193])
ch = np.linalg.cholesky(a4)
y4 = np.linalg.solve(ch, a4_right)
print(np.linalg.solve(ch.T, y4))

[ 6. -5. -4.]
